"""agregar columna activo a tabla proveedores

Revision ID: 4e13f273a615
Revises: 
Create Date: 2026-08-14 02:34:39.939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e13f273a615'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'proveedores',
        sa.Column(
            'activo',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("1"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###